# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "wl" "mba6x_backlight" ];
  boot.extraModulePackages = [ pkgs.linuxPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0724ae1a-9a53-49bc-bda6-6acbb4e6944a";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ec4a0f5b-dbb9-4e80-ada2-5717147364ff";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1CA6-C86D";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/36f9c50f-3728-4d4c-903b-c844192e13b5"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
